/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pseudocode.compiler;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.nio.channels.FileChannel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Mohammed
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public PseudocodeCompiler pseudocodeCompiler;
    public Parser parser;

    public MainJFrame() {
        initComponents();
        setTitle("Pseudocode Compiler");
        setSize(847, 650);
        setLocation(550, 150);
        setResizable(false);
        updateLineNumbers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lexicalAnalysis = new javax.swing.JButton();
        syntaxAnalysis = new javax.swing.JButton();
        semanticAnalysis = new javax.swing.JButton();
        openOutput = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        inputAreaScrollPane = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lexicalAnalysis.setBackground(new java.awt.Color(42, 172, 227));
        lexicalAnalysis.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lexicalAnalysis.setForeground(new java.awt.Color(255, 255, 255));
        lexicalAnalysis.setText("Lexical Analysis");
        lexicalAnalysis.setBorderPainted(false);
        lexicalAnalysis.setFocusPainted(false);
        lexicalAnalysis.setFocusable(false);
        lexicalAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lexicalAnalysisActionPerformed(evt);
            }
        });

        syntaxAnalysis.setBackground(new java.awt.Color(42, 172, 227));
        syntaxAnalysis.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        syntaxAnalysis.setForeground(new java.awt.Color(255, 255, 255));
        syntaxAnalysis.setBorderPainted(false);
        syntaxAnalysis.setFocusPainted(false);
        syntaxAnalysis.setFocusable(false);
        syntaxAnalysis.setLabel("Syntax Analysis");
        syntaxAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syntaxAnalysisActionPerformed(evt);
            }
        });

        semanticAnalysis.setBackground(new java.awt.Color(204, 204, 204));
        semanticAnalysis.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        semanticAnalysis.setForeground(new java.awt.Color(255, 255, 255));
        semanticAnalysis.setText("Semantic Analysis");
        semanticAnalysis.setBorderPainted(false);
        semanticAnalysis.setEnabled(false);
        semanticAnalysis.setFocusPainted(false);
        semanticAnalysis.setFocusable(false);
        semanticAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semanticAnalysisActionPerformed(evt);
            }
        });

        openOutput.setBackground(new java.awt.Color(0, 153, 102));
        openOutput.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        openOutput.setForeground(new java.awt.Color(255, 255, 255));
        openOutput.setText("Open output");
        openOutput.setBorderPainted(false);
        openOutput.setFocusPainted(false);
        openOutput.setFocusable(false);
        openOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openOutputActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pseudocode/compiler/Compiler_icon.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 172, 227));
        jLabel1.setText("Pseudocode Compiler");

        Exit.setBackground(new java.awt.Color(153, 0, 0));
        Exit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Exit");
        Exit.setBorderPainted(false);
        Exit.setFocusPainted(false);
        Exit.setFocusable(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane3.setViewportView(outputArea);

        inputArea.setColumns(20);
        inputArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputArea.setForeground(new java.awt.Color(51, 51, 51));
        inputArea.setRows(5);
        inputAreaScrollPane.setViewportView(inputArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                            .addComponent(inputAreaScrollPane))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(semanticAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lexicalAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(syntaxAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(openOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 236, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lexicalAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(syntaxAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semanticAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(inputAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(openOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void lex() {
        String input = inputArea.getText();
        String filePath = "input.txt";
        try {
            FileWriter fileWriter = new FileWriter(filePath);
            BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
            bufferedWriter.write(input);
            bufferedWriter.newLine();
            bufferedWriter.close();
        } catch (IOException e) {
            System.out.println("Error writing to input file");
        }
        pseudocodeCompiler = new PseudocodeCompiler();
        outputArea.setText("");
        if (pseudocodeCompiler.errorMessage == null) {
            outputArea.setText("Lexer Completed Successfully...");
        } else {
            outputArea.setText(pseudocodeCompiler.errorMessage);
        }

    }

    private void lexicalAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lexicalAnalysisActionPerformed
        lex();
        try {
            PrintWriter printWriter = new PrintWriter("output.txt");
            BufferedReader bufferdReader = new BufferedReader(new FileReader("lexerOutput.txt"));
            String line;
            try {
                line = bufferdReader.readLine();
                while (line != null) {
                    printWriter.println(line);
                    line = bufferdReader.readLine();
                }
                printWriter.flush();
                bufferdReader.close();
                printWriter.close();
            } catch (IOException ex) {
            }

        } catch (FileNotFoundException ex) {

        }
    }//GEN-LAST:event_lexicalAnalysisActionPerformed

    private void syntaxAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syntaxAnalysisActionPerformed
        lex();
        try {
            Parser parser = new Parser();
            parser.parse();
            if (parser.errorMessage == null) {
                outputArea.setText(outputArea.getText() + "\nParser Completed Successfully...");
            } else {
                outputArea.setText("");
                outputArea.setText(parser.errorMessage);
            }
        } catch (Exception ex) {
        }
        generateOutput();

    }//GEN-LAST:event_syntaxAnalysisActionPerformed

    private void generateOutput() {
        try {
            PrintWriter printWriter = new PrintWriter("output.txt");
            BufferedReader bufferdReader = new BufferedReader(new FileReader("lexerOutput.txt"));
            String line;
            try {
                line = bufferdReader.readLine();
                while (line != null) {
                    printWriter.println(line);
                    line = bufferdReader.readLine();
                }
                bufferdReader = new BufferedReader(new FileReader("parserOutput.txt"));
                line = bufferdReader.readLine();
                while (line != null) {
                    printWriter.println(line);
                    line = bufferdReader.readLine();
                }
                printWriter.flush();
                bufferdReader.close();
                printWriter.close();
            } catch (IOException ex) {
            }

        } catch (FileNotFoundException ex) {

        }
    }


    private void semanticAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semanticAnalysisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semanticAnalysisActionPerformed

    private void openOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openOutputActionPerformed
        try {
            PrintWriter writer = new PrintWriter("tempOutput.txt", "UTF-8");
            copyFile("output.txt", "tempOutput.txt");
            BufferedWriter bw = new BufferedWriter(writer);
            bw.close();
            File tempOutput = new File("tempOutput.txt");
            Desktop.getDesktop().open(tempOutput);

        } catch (FileNotFoundException | UnsupportedEncodingException f) {
        } catch (IOException i) {
        }
    }//GEN-LAST:event_openOutputActionPerformed

    public void copyFile(String sourceFile, String destFile) throws IOException {

        FileChannel source = null;
        FileChannel destination = null;

        try {
            source = new FileInputStream(sourceFile).getChannel();
            destination = new FileOutputStream(destFile).getChannel();
            destination.transferFrom(source, 0, source.size());
        } finally {
            if (source != null) {
                source.close();
            }
            if (destination != null) {
                destination.close();
            }
        }

    }

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JTextArea inputArea;
    private javax.swing.JScrollPane inputAreaScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton lexicalAnalysis;
    private javax.swing.JButton openOutput;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JButton semanticAnalysis;
    private javax.swing.JButton syntaxAnalysis;
    // End of variables declaration//GEN-END:variables

    private void updateLineNumbers() {
        LineNumberingTextArea lineNumberingTextArea = new LineNumberingTextArea(inputArea);

        inputAreaScrollPane.setRowHeaderView(lineNumberingTextArea);

        inputArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent documentEvent) {
                lineNumberingTextArea.updateLineNumbers();
            }

            @Override
            public void removeUpdate(DocumentEvent documentEvent) {
                lineNumberingTextArea.updateLineNumbers();
            }

            @Override
            public void changedUpdate(DocumentEvent documentEvent) {
                lineNumberingTextArea.updateLineNumbers();
            }
        });
    }

}
